# Generated by Django 2.2.3 on 2019-08-22 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='rcreated')),
                ('dropped_at', models.DateTimeField(blank=True, db_column='rdropped', null=True)),
                ('mqtt', models.CharField(db_column='mqttid', max_length=255, unique=True)),
                ('name', models.CharField(max_length=64, verbose_name='название')),
                ('description', models.CharField(blank=True, max_length=500)),
                ('device_type', models.IntegerField(db_column='type', default=0)),
                ('config', models.CharField(blank=True, max_length=2000)),
            ],
            options={
                'db_table': 'devices',
            },
        ),
        migrations.CreateModel(
            name='DeviceGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='rcreated')),
                ('dropped_at', models.DateTimeField(blank=True, db_column='rdropped', null=True)),
                ('name', models.CharField(max_length=64)),
                ('rights', models.IntegerField(default=0)),
                ('description', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'db_table': 'devicegroup',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='rcreated')),
                ('dropped_at', models.DateTimeField(blank=True, db_column='rdropped', null=True)),
                ('guid', models.UUIDField(db_column='userid', default=uuid.uuid4, editable=False)),
                ('last_name', models.CharField(db_column='surname', max_length=64)),
                ('first_name', models.CharField(db_column='firstname', max_length=64)),
                ('patronymic', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='rcreated')),
                ('dropped_at', models.DateTimeField(blank=True, db_column='rdropped', null=True)),
                ('guid', models.UUIDField(db_column='companyid', default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='название')),
                ('address', models.CharField(blank=True, max_length=500)),
                ('phone', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('role', models.CharField(blank=True, choices=[('adm', 'admin'), ('ctrl', 'controller'), ('reg', 'registrator'), ('none', 'not selected')], max_length=4)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='idenick_app.Organization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='rcreated')),
                ('dropped_at', models.DateTimeField(blank=True, db_column='rdropped', null=True)),
                ('moment', models.DateTimeField(auto_now_add=True, db_column='stamp')),
                ('request_type', models.IntegerField(db_column='request', default=0)),
                ('response_type', models.IntegerField(db_column='result', default=0)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('algorithm_type', models.IntegerField(db_column='algorithm', default=0)),
                ('device', models.ForeignKey(db_column='deviceid', on_delete=django.db.models.deletion.CASCADE, to='idenick_app.Device')),
                ('employee', models.ForeignKey(db_column='userid', on_delete=django.db.models.deletion.CASCADE, to='idenick_app.Employee')),
            ],
            options={
                'db_table': 'querylog',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='organization',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='idenick_app.Organization'),
        ),
        migrations.AddField(
            model_name='device',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='idenick_app.Organization'),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='rcreated')),
                ('dropped_at', models.DateTimeField(blank=True, db_column='rdropped', null=True)),
                ('name', models.CharField(max_length=64)),
                ('rights', models.IntegerField(default=0)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('organization', models.ForeignKey(db_column='companyid', on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='idenick_app.Organization')),
            ],
            options={
                'db_table': 'usergroup',
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Employee2Department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='rcreated')),
                ('dropped_at', models.DateTimeField(blank=True, db_column='rdropped', null=True)),
                ('department', models.ForeignKey(db_column='usergroupid', on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='idenick_app.Department')),
                ('employee', models.ForeignKey(db_column='usersid', on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='idenick_app.Employee')),
            ],
            options={
                'db_table': 'users_usergroup',
                'unique_together': {('department', 'employee')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='device',
            unique_together={('organization', 'name')},
        ),
    ]
