# Generated by Django 2.2.3 on 2019-08-22 14:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('idenick_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeerequest',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='employeerequest',
            name='dropped_at',
        ),
        migrations.AddField(
            model_name='devicegroup',
            name='organization',
            field=models.ForeignKey(db_column='companyid', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='device_groups', to='idenick_app.Organization'),
        ),
        migrations.AddField(
            model_name='employeerequest',
            name='templatesid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='employee',
            name='guid',
            field=models.CharField(db_column='userid', default=uuid.uuid4, editable=False, max_length=64, unique=True),
        ),
    ]
