# Generated by Django 2.2.3 on 2019-08-22 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idenick_app', '0002_auto_20190822_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicegroup',
            name='organization',
            field=models.ForeignKey(db_column='companyid', on_delete=django.db.models.deletion.CASCADE, related_name='device_groups', to='idenick_app.Organization'),
        ),
    ]
