# Generated by Django 2.2.3 on 2019-08-22 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idenick_app', '0004_auto_20190822_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeerequest',
            name='device',
            field=models.ForeignKey(db_column='devicesid', on_delete=django.db.models.deletion.CASCADE, to='idenick_app.Device'),
        ),
    ]
