# Generated by Django 2.2.3 on 2019-08-22 14:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('idenick_app', '0005_auto_20190822_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='guid',
            field=models.CharField(db_column='companyid', default=uuid.uuid4, editable=False, max_length=64, unique=True),
        ),
    ]
