# Generated by Django 2.2.3 on 2019-08-28 10:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('idenick_app', '0006_auto_20190822_2251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicegroup',
            name='organization',
        ),
        migrations.AlterField(
            model_name='employee',
            name='guid',
            field=models.CharField(db_column='userid', default=uuid.uuid4, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='employeerequest',
            name='device',
            field=models.ForeignKey(db_column='devicesid', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='idenick_app.Device'),
        ),
        migrations.AlterField(
            model_name='employeerequest',
            name='employee',
            field=models.ForeignKey(db_column='usersid', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='idenick_app.Employee'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='guid',
            field=models.CharField(db_column='companyid', default=uuid.uuid4, editable=False, max_length=50, unique=True),
        ),
    ]
