# Generated by Django 2.2.3 on 2019-09-03 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idenick_app', '0007_auto_20190828_1816'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicegroup',
            options={'verbose_name': 'Проходная', 'verbose_name_plural': 'Проходные'},
        ),
        migrations.AlterField(
            model_name='devicegroup',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='название проходной'),
        ),
        migrations.CreateModel(
            name='DeviceGroup2Organization',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='rcreated')),
                ('dropped_at', models.DateTimeField(blank=True, db_column='rdropped', null=True)),
                ('device_group', models.ForeignKey(db_column='devicegroupsid', on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to='idenick_app.DeviceGroup')),
                ('organization', models.ForeignKey(db_column='organizationsid', on_delete=django.db.models.deletion.CASCADE, related_name='device_groups', to='idenick_app.Organization')),
            ],
            options={
                'unique_together': {('device_group', 'organization')},
            },
        ),
        migrations.CreateModel(
            name='Device2DeviceGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='rcreated')),
                ('dropped_at', models.DateTimeField(blank=True, db_column='rdropped', null=True)),
                ('device', models.ForeignKey(db_column='devicesid', on_delete=django.db.models.deletion.CASCADE, related_name='device_groups', to='idenick_app.Device')),
                ('device_group', models.ForeignKey(db_column='devicegroupsid', on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='idenick_app.DeviceGroup')),
            ],
            options={
                'unique_together': {('device', 'device_group')},
            },
        ),
    ]
