# Generated by Django 2.2.3 on 2019-09-04 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idenick_app', '0009_auto_20190904_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device2Organization',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='rcreated')),
                ('dropped_at', models.DateTimeField(blank=True, db_column='rdropped', null=True)),
                ('device', models.ForeignKey(db_column='devicesid', on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to='idenick_app.Device')),
                ('organization', models.ForeignKey(db_column='companysid', on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='idenick_app.Organization')),
            ],
            options={
                'unique_together': {('device', 'organization')},
            },
        ),
    ]
