# Generated by Django 2.2.3 on 2019-09-05 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idenick_app', '0010_device2organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicegroup2organization',
            name='organization',
            field=models.ForeignKey(db_column='companyid', on_delete=django.db.models.deletion.CASCADE, related_name='device_groups', to='idenick_app.Organization'),
        ),
    ]
