# Generated by Django 2.2.3 on 2019-09-05 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idenick_app', '0011_auto_20190905_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='organization',
        ),
        migrations.CreateModel(
            name='Employee2Organization',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='rcreated')),
                ('dropped_at', models.DateTimeField(blank=True, db_column='rdropped', null=True)),
                ('employee', models.ForeignKey(db_column='usersid', on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to='idenick_app.Employee')),
                ('organization', models.ForeignKey(db_column='companyid', on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='idenick_app.Organization')),
            ],
            options={
                'unique_together': {('employee', 'organization')},
            },
        ),
    ]
