# Generated by Django 2.2.5 on 2019-09-30 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idenick_app', '0012_auto_20190905_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='device_group',
        ),
        migrations.AlterField(
            model_name='device2devicegroup',
            name='device_group',
            field=models.ForeignKey(db_column='devicegroupid', on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='idenick_app.DeviceGroup'),
        ),
        migrations.AlterModelTable(
            name='device2devicegroup',
            table='devices_devicegroup',
        ),
    ]
