# Generated by Django 2.2.5 on 2019-10-22 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idenick_app', '0013_auto_20190930_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeerequest',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='employeerequest',
            name='templatesid',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
