# Generated by Django 2.2.5 on 2019-10-28 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idenick_app', '0014_auto_20191023_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeerequest',
            name='algorithm_type',
            field=models.IntegerField(choices=[(0, 'Не существующий тип пакета'), (1, 'По отпечатку, возможно в основе его лежит стороний алгоритм'), (2, 'По отпечатку, основной используемый алгоритм идентификации'), (3, 'По отпечатку, не реализован в настоящей сборке'), (4, 'Не распознавание лиц'), (5, 'По номеру карты, дополнительный используемый алгоритм идентификации')], db_column='algorithm'),
        ),
        migrations.AlterField(
            model_name='employeerequest',
            name='device',
            field=models.ForeignKey(db_column='devicesid', null=True, on_delete=django.db.models.deletion.CASCADE, to='idenick_app.Device'),
        ),
        migrations.AlterField(
            model_name='employeerequest',
            name='employee',
            field=models.ForeignKey(db_column='usersid', null=True, on_delete=django.db.models.deletion.CASCADE, to='idenick_app.Employee'),
        ),
        migrations.AlterField(
            model_name='employeerequest',
            name='request_type',
            field=models.IntegerField(choices=[(0, 'Не существующий тип пакета'), (1, 'Запрошенная команда не поддерживается'), (2, 'Запрос версии протокола или PING сервера'), (3, 'Запрос версии протокола или PING сервера'), (10, 'Запрос на удаление записи по изображению отпечатка'), (11, 'Запрос на регистрацию записи по изображению отпечатка'), (12, 'Запрос на поиск записи по изображению ранее зарегистрированного отпечатка'), (20, 'Запрос на удаление записи по идентификатору, полученному со считывателя карт'), (21, 'Запрос на регистрацию записи по идентификатору, полученному со считывателя карт'), (22, 'Запрос на поиск записи по идентификатору, полученному со считывателя карт'), (30, 'Запрос на удаление записи по шаблону отпечатка'), (31, 'Запрос на регистрацию записи по шаблону отпечатка'), (32, 'Запрос на поиск записи по ранее зарегистрированному шаблону отпечатка'), (40, 'Запрос на удаление записи по изображению лица'), (41, 'Запрос на регистрацию записи по изображению лица'), (42, 'Запрос на поиск записи по изображению ранее зарегистрированного лица')], db_column='request'),
        ),
        migrations.AlterField(
            model_name='employeerequest',
            name='response_type',
            field=models.IntegerField(choices=[(0, 'Не существующий тип пакета'), (1, 'Запрошенная команда не поддерживается'), (2, 'Ошибка при выполнении запроса'), (2, 'Запрос версии или PING сервера'), (10, 'Удаление отпечатка выполнено успешно'), (11, 'Регистрация выполнена успешно'), (12, 'Найдено совпадение'), (13, 'Регистрация невозможна так как обнаружено совпадение'), (14, 'Идентификация невозможна из-за низкого качества идентификационных данных'), (15, 'Совпадение отпечатка не обнаружено среди ранее зарегистрированных шаблонов')], db_column='result'),
        ),
        migrations.AlterField(
            model_name='employeerequest',
            name='templatesid',
            field=models.IntegerField(null=True),
        ),
    ]
