# Generated by Django 2.2.3 on 2019-11-29 19:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idenick_app', '0016_auto_20191128_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='timezone',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name='organization',
            name='timezone',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
