# Generated by Django 2.2.5 on 2019-12-05 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idenick_app', '0018_auto_20191203_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='dropped_at',
            field=models.DateTimeField(blank=True, db_column='rdropped', null=True),
        ),
    ]
