# Generated by Django 2.2.5 on 2019-12-10 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idenick_app', '0019_login_dropped_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_group',
            field=models.ForeignKey(blank=True, db_column='devicegroupsid', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='idenick_app.DeviceGroup'),
        ),
        migrations.DeleteModel(
            name='Device2DeviceGroup',
        ),
    ]
