# Generated by Django 2.2.3 on 2019-12-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idenick_app', '0020_auto_20191210_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='show_in_report',
            field=models.BooleanField(default=False),
        ),
    ]
