# Generated by Django 2.2.3 on 2020-01-21 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idenick_app', '0021_department_show_in_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee2organization',
            name='timesheet_end',
            field=models.CharField(blank=True, default=None, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='employee2organization',
            name='timesheet_start',
            field=models.CharField(blank=True, default=None, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='timesheet_end',
            field=models.CharField(blank=True, default=None, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='timesheet_start',
            field=models.CharField(blank=True, default=None, max_length=5, null=True),
        ),
    ]
