# Generated by Django 2.2.5 on 2020-03-03 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idenick_app', '0024_auto_20200303_1627'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeviceGroup',
            new_name='Checkpoint',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='device_group',
            new_name='checkpoint',
        ),
        migrations.RenameField(
            model_name='devicegroup2organization',
            old_name='device_group',
            new_name='checkpoint',
        ),
        migrations.AlterField(
            model_name='devicegroup2organization',
            name='organization',
            field=models.ForeignKey(db_column='companyid', on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='idenick_app.Organization'),
        ),
        migrations.AlterUniqueTogether(
            name='devicegroup2organization',
            unique_together={('checkpoint', 'organization')},
        ),
    ]
