# Generated by Django 2.2.5 on 2020-03-03 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idenick_app', '0025_auto_20200303_1707'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeviceGroup2Organization',
            new_name='Checkpoint2Organization',
        ),
    ]
