# Generated by Django 2.2.5 on 2020-03-06 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idenick_app', '0026_auto_20200303_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkpoint',
            name='dropped_at',
            field=models.DateTimeField(blank=True, db_column='rdropped', db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='checkpoint',
            name='id',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='checkpoint2organization',
            name='dropped_at',
            field=models.DateTimeField(blank=True, db_column='rdropped', db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='checkpoint2organization',
            name='id',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='department',
            name='dropped_at',
            field=models.DateTimeField(blank=True, db_column='rdropped', db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='department',
            name='show_in_report',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='device',
            name='dropped_at',
            field=models.DateTimeField(blank=True, db_column='rdropped', db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='id',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='device2organization',
            name='dropped_at',
            field=models.DateTimeField(blank=True, db_column='rdropped', db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='device2organization',
            name='id',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='dropped_at',
            field=models.DateTimeField(blank=True, db_column='rdropped', db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(db_column='firstname', db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(db_column='surname', db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='employee',
            name='patronymic',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='employee2department',
            name='dropped_at',
            field=models.DateTimeField(blank=True, db_column='rdropped', db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee2department',
            name='id',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employee2organization',
            name='dropped_at',
            field=models.DateTimeField(blank=True, db_column='rdropped', db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee2organization',
            name='id',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employeerequest',
            name='id',
            field=models.AutoField(db_index=True, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employeerequest',
            name='moment',
            field=models.DateTimeField(auto_now_add=True, db_column='stamp', db_index=True),
        ),
        migrations.AlterField(
            model_name='indentificationtepmplate',
            name='algorithm_type',
            field=models.IntegerField(choices=[(0, 'Не существующий тип пакета'), (1, 'По отпечатку, возможно в основе его лежит стороний алгоритм'), (2, 'По отпечатку, основной используемый алгоритм идентификации'), (3, 'По отпечатку, не реализован в настоящей сборке'), (4, 'Не распознавание лиц'), (10, 'Фото сотрудника, не используется для авторизации'), (5, 'По номеру карты, дополнительный используемый алгоритм идентификации')], db_column='algorithm', db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name='indentificationtepmplate',
            name='dropped_at',
            field=models.DateTimeField(blank=True, db_column='rdropped', db_index=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='dropped_at',
            field=models.DateTimeField(blank=True, db_column='rdropped', db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='id',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='organization',
            name='dropped_at',
            field=models.DateTimeField(blank=True, db_column='rdropped', db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='id',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(db_index=True, max_length=250, unique=True, verbose_name='название'),
        ),
    ]
