# Generated by Django 2.2.5 on 2020-03-06 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idenick_app', '0027_auto_20200306_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indentificationtepmplate',
            name='algorithm_type',
            field=models.SmallIntegerField(choices=[(0, 'Не существующий тип пакета'), (1, 'По отпечатку, возможно в основе его лежит стороний алгоритм'), (2, 'По отпечатку, основной используемый алгоритм идентификации'), (3, 'По отпечатку, не реализован в настоящей сборке'), (4, 'Не распознавание лиц'), (10, 'Фото сотрудника, не используется для авторизации'), (5, 'По номеру карты, дополнительный используемый алгоритм идентификации')], db_column='algorithm', db_index=True),
        ),
        migrations.AlterField(
            model_name='indentificationtepmplate',
            name='algorithm_version',
            field=models.SmallIntegerField(db_column='algorithmVersion'),
        ),
        migrations.AlterField(
            model_name='indentificationtepmplate',
            name='config',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='indentificationtepmplate',
            name='dropped_at',
            field=models.DateTimeField(blank=True, db_column='rdropped', db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='indentificationtepmplate',
            name='employee',
            field=models.ForeignKey(db_column='usersid', on_delete=django.db.models.deletion.CASCADE, to='idenick_app.Employee'),
        ),
        migrations.AlterField(
            model_name='indentificationtepmplate',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='indentificationtepmplate',
            name='quality',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='indentificationtepmplate',
            name='template',
            field=models.BinaryField(),
        ),
    ]
