# Generated by Django 3.0.4 on 2020-03-20 17:49

from django.db import migrations
import idenick_app.classes.utils.models_utils


class Migration(migrations.Migration):

    dependencies = [
        ('idenick_app', '0028_auto_20200306_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indentificationtepmplate',
            name='algorithm_version',
            field=idenick_app.classes.utils.models_utils.TinyIntegerField(db_column='algorithmVersion'),
        ),
        migrations.AlterField(
            model_name='indentificationtepmplate',
            name='quality',
            field=idenick_app.classes.utils.models_utils.TinyIntegerField(blank=True, default=0, null=True),
        ),
    ]
